version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto21
    build:
        commands:
            - mvn -DskipTests=true clean package
artifacts:
    files:
        - target/training-0.0.1-SNAPSHOT.jar