spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://awseb-e-7uu9p5mkvt-stack-awsebrdsdatabase-nmgpwszhsztf.crmc26mo4ysc.eu-north-1.rds.amazonaws.com:5432/postgres
        username: rootroot
        password: rootroot
springdoc:
    api-docs:
        path: "/api-docs"

rsa:
    private-key: classpath:cert/private.pem
    public-key: classpath:cert/public.pem

server:
    port: 5000