spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root
springdoc:
    api-docs:
        path: "/api-docs"

rsa:
    private-key: classpath:cert/private.pem
    public-key: classpath:cert/public.pem

server:
    port: 5000